#include "cheatsetup.hpp"
#include "ModuleManager.hpp"
#include "SpinAttack/SpinAttack.hpp"
#include "Blink/Blink.hpp"
#include "cheat/AntiVoid/AntiVoid.hpp"
#include "cheat/ChestAura/ChestAura.hpp"
#include "cheat/ClickGUI/ClickGUI.hpp"
#include "cheat/Criticals/Criticals.hpp"
#include "cheat/Fly/Fly.hpp"
#include "cheat/Fucker/Fucker.hpp"
#include "cheat/GameMode/GameMode.hpp"
#include "cheat/GodMode/GodMode.hpp"
#include "cheat/HitBox/HitBox.hpp"
#include "cheat/Hud/Hud.hpp"
#include "cheat/InfiniteAura/InfiniteAura.hpp"
#include "cheat/JetPack/JetPack.hpp"
#include "cheat/KillAura/KillAura.hpp"
#include "cheat/Network/Network.hpp"
#include "cheat/NoPacket/NoPacket.hpp"
#include "cheat/NoSwing/NoSwing.hpp"
#include "cheat/Nuker/Nuker.hpp"
#include "cheat/Scaffold/Scaffold.hpp"
#include "cheat/Seckill/Seckill.hpp"
#include "cheat/Speed/Speed.hpp"
#include "cheat/Strafe/Strafe.hpp"
#include "cheat/Teams/Teams.hpp"
#include "cheat/Teleport/Teleport.hpp"
#include "cheat/Timer/Timer.hpp"
#include "cheat/Velocity/Velocity.hpp"
void cheatSetup() {
  ModuleManager::addModule(new cheat::SpinAttack);
  ModuleManager::addModule(new cheat::Blink);
  ModuleManager::addModule(new cheat::Timer);
  ModuleManager::addModule(new cheat::Network);
  ModuleManager::addModule(new cheat::GodMode);
  ModuleManager::addModule(new cheat::ClickGUI);
  ModuleManager::addModule(new cheat::Seckill);
  ModuleManager::addModule(new cheat::KillAura);
  ModuleManager::addModule(new cheat::Velocity);
  ModuleManager::addModule(new cheat::Scaffold);
  ModuleManager::addModule(new cheat::NoPacket);
  ModuleManager::addModule(new cheat::Fly);
  ModuleManager::addModule(new cheat::Speed);
  ModuleManager::addModule(new cheat::Hud);
  ModuleManager::addModule(new cheat::Strafe);
  ModuleManager::addModule(new cheat::InfiniteAura);
  ModuleManager::addModule(new cheat::NoSwing);
  ModuleManager::addModule(new cheat::Teams);
  ModuleManager::addModule(new cheat::AntiVoid);
  ModuleManager::addModule(new cheat::Nuker);
  ModuleManager::addModule(new cheat::Fucker);
  ModuleManager::addModule(new cheat::JetPack);
  ModuleManager::addModule(new cheat::ChestAura);
  ModuleManager::addModule(new cheat::Teleport);
  ModuleManager::addModule(new cheat::Criticals);
  ModuleManager::addModule(new cheat::HitBox);
  ModuleManager::addModule(new cheat::GameMode);
}