name: build

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.9.6'
        actions-cache-folder: '.xmake-cache'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27c
        local-cache: true
    - name: 编译软件
      run: |
        xmake f --host=android -m release -a arm64-v8a -p android -y
        xmake -j8 -y -b cheat
    - uses: actions/upload-artifact@v4
      with:
        name: cheat
        path: |
          build/android